#publish your docker image to github container registry
name: publish

on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the composability fun Docker image
        run: |
          docker build . --tag ghcr.io/blackgirlbytes/composability-fun:latest
          docker run ghcr.io/blackgirlbytes/composability-fun:latest
          docker push ghcr.io/blackgirlbytes/composability-fun:latest